auth_db:
    host: localhost
    port: 3306
    username: root
    password: HeavenBlessesHardwork
    db: auth_db
api_db:
    host: localhost
    port: 3306
    username: root
    password: HeavenBlessesHardwork
    db: api_db
server_settings:
    jwt_key: secret
    token_expiry_minutes: -1